version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/official-gsm-client-server
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:

    - location: !If [ ${var:group} == "official-client-test-server", "/scripts/dev-deploy.sh", "/scripts/prod-deploy.sh" ]
      timeout: 60
      runas: root
