version: "3.3"

services:

  app:
    image: official-test-server:client
    expose:
      - 56829
    ports:
      - "56829:8080"
    logging:
      driver: awslogs
      options:
        awslogs-group: "official-admin-test"
        awslogs-region: "ap-northeast-2"
        awslogs-stream: "client-spring-logging"